root = "." # Projenin kök dizini
tmp_dir = "tmp" # Air'ın geçici dosyaları saklayacağı geçici dizin

[build] # Derleme yapılandırması
  bin = "main" # Derlendikten sonra oluşturulacak ikili dosyanın adı
  cmd = "go build -o {{.Output}} {{.Input}}" # Projeyi derleme komutu
  exclude = ["tmp/*", "client/**/node_modules/**", "client/dist/*"] # İzleme dışı bırakılacak dizinler
  include = ["**/*.go"] # İzleme için dahil edilecek dosya kalıpları
  ignore = ["tmp/*"] # Derleme tetiklenmesi için göz ardı edilecek dosya veya dizinler
